import SwiftUI

extension AppShellView {
    func makeHomeScreen(
        stations: [Station],
        isLoading: Bool,
        errorMessage: String?,
        recentStations: [Station],
        favoriteStations: [Station],
        lastPlayedStation: Station?,
        discoveries: [DiscoveredTrack],
        stationFeedback: [String: TuneAVStationFeedback],
        feedContext: HomeFeedContext,
        preferredTag: String,
        preferredCountryCode: String,
        bottomContentPadding: CGFloat,
        favoriteStationIDs: Set<String>,
        nowPlayingTracks: [String: NowPlayingTrack],
        openAvi: @escaping () -> Void,
        openSearchTag: @escaping (String) -> Void,
        refreshHome: @escaping () async -> Void,
        playStation: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?) -> Void,
        toggleFavorite: @escaping (Station) -> Void,
        setStationFeedback: @escaping (Station, TuneAVStationFeedback?) -> Void,
        showStationDetails: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?) -> Void
    ) -> some View {
        HomeScreen(
            stations: stations,
            isLoading: isLoading,
            errorMessage: errorMessage,
            recentStations: recentStations,
            favoriteStations: favoriteStations,
            lastPlayedStation: lastPlayedStation,
            discoveries: discoveries,
            stationFeedback: stationFeedback,
            feedContext: feedContext,
            preferredTag: preferredTag,
            preferredCountryCode: preferredCountryCode,
            bottomContentPadding: bottomContentPadding,
            favoriteStationIDs: favoriteStationIDs,
            nowPlayingTracks: nowPlayingTracks,
            openAvi: openAvi,
            openSearchTag: openSearchTag,
            refreshHome: refreshHome,
            playStation: playStation,
            toggleFavorite: toggleFavorite,
            setStationFeedback: setStationFeedback,
            showStationDetails: showStationDetails
        )
    }

    func makeSearchScreen(
        query: Binding<String>,
        activeTag: Binding<String?>,
        selectedCountryCode: Binding<String?>,
        discoveryMode: Binding<TuneAVStationDiscoveryMode>,
        results: [Station],
        isLoading: Bool,
        isLoadingMore: Bool,
        totalCount: Int?,
        hasMoreResults: Bool,
        errorMessage: String?,
        tags: [String],
        bottomContentPadding: CGFloat,
        favoriteStationIDs: Set<String>,
        nowPlayingTracks: [String: NowPlayingTrack],
        stationFeedback: [String: TuneAVStationFeedback],
        playStation: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?) -> Void,
        toggleFavorite: @escaping (Station) -> Void,
        showStationDetails: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?) -> Void,
        loadMoreResults: @escaping () -> Void
    ) -> some View {
        SearchScreen(
            query: query,
            activeTag: activeTag,
            selectedCountryCode: selectedCountryCode,
            discoveryMode: discoveryMode,
            results: results,
            isLoading: isLoading,
            isLoadingMore: isLoadingMore,
            totalCount: totalCount,
            hasMoreResults: hasMoreResults,
            errorMessage: errorMessage,
            tags: tags,
            bottomContentPadding: bottomContentPadding,
            favoriteStationIDs: favoriteStationIDs,
            nowPlayingTracks: nowPlayingTracks,
            stationFeedback: stationFeedback,
            playStation: playStation,
            toggleFavorite: toggleFavorite,
            showStationDetails: showStationDetails,
            loadMoreResults: loadMoreResults
        )
    }

    func makeLibraryScreen(
        favorites: [Station],
        recents: [Station],
        discoveries: [DiscoveredTrack],
        summary: TuneAVUserSummary?,
        requestedMode: Binding<RadioLibraryMode?>,
        requestedOverview: Binding<Bool?>,
        bottomContentPadding: CGFloat,
        favoriteStationIDs: Set<String>,
        nowPlayingTracks: [String: NowPlayingTrack],
        stationFeedback: [String: TuneAVStationFeedback],
        openAccountAction: @escaping () -> Void,
        startSignInAction: @escaping () -> Void,
        openSearchAction: @escaping () -> Void,
        playStation: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?) -> Void,
        toggleFavorite: @escaping (Station) -> Void,
        showStationDetails: @escaping (Station, TuneAVPlaybackQueueSource, [Station]?, RadioLibraryMode?, Bool?) -> Void
    ) -> some View {
        LibraryScreen(
            favorites: favorites,
            recents: recents,
            discoveries: discoveries,
            summary: summary,
            requestedMode: requestedMode,
            requestedOverview: requestedOverview,
            bottomContentPadding: bottomContentPadding,
            favoriteStationIDs: favoriteStationIDs,
            nowPlayingTracks: nowPlayingTracks,
            stationFeedback: stationFeedback,
            openAccountAction: openAccountAction,
            startSignInAction: startSignInAction,
            openSearchAction: openSearchAction,
            playStation: playStation,
            toggleFavorite: toggleFavorite,
            showStationDetails: showStationDetails
        )
    }

    func makeMusicScreen(
        discoveries: [DiscoveredTrack],
        summary: TuneAVUserSummary?,
        historyStationFilter: Binding<Station?>,
        requestedMusicMode: Binding<MusicContentMode?>,
        requestedMusicOverview: Binding<Bool?>,
        bottomContentPadding: CGFloat,
        openDiscoveryStation: @escaping (DiscoveredTrack) -> Void,
        openDiscoveryStationInfo: @escaping (DiscoveredTrack) -> Void,
        openDiscoveryInfo: @escaping (DiscoveredTrack, MusicContentMode?) -> Void,
        openArtistInfo: @escaping (DiscoveryArtistSummary, MusicContentMode?) -> Void,
        stationArtworkURL: @escaping (DiscoveredTrack) -> URL?,
        trackFeedback: @escaping (DiscoveredTrack) -> TuneAVStationFeedback?,
        openSearchAction: @escaping () -> Void,
        openAccountAction: @escaping () -> Void,
        startSignInAction: @escaping () -> Void,
        toggleDiscoverySaved: @escaping (DiscoveredTrack) -> Void,
        hideDiscovery: @escaping (DiscoveredTrack) -> Void,
        restoreDiscovery: @escaping (DiscoveredTrack) -> Void,
        removeDiscovery: @escaping (DiscoveredTrack) -> Void,
        clearDiscoveries: @escaping () -> Void
    ) -> some View {
        MusicScreen(
            discoveries: discoveries,
            summary: summary,
            historyStationFilter: historyStationFilter,
            requestedMusicMode: requestedMusicMode,
            requestedMusicOverview: requestedMusicOverview,
            bottomContentPadding: bottomContentPadding,
            openDiscoveryStation: openDiscoveryStation,
            openDiscoveryStationInfo: openDiscoveryStationInfo,
            openDiscoveryInfo: openDiscoveryInfo,
            openArtistInfo: openArtistInfo,
            stationArtworkURL: stationArtworkURL,
            trackFeedback: trackFeedback,
            openSearchAction: openSearchAction,
            openAccountAction: openAccountAction,
            startSignInAction: startSignInAction,
            toggleDiscoverySaved: toggleDiscoverySaved,
            hideDiscovery: hideDiscovery,
            restoreDiscovery: restoreDiscovery,
            removeDiscovery: removeDiscovery,
            clearDiscoveries: clearDiscoveries
        )
    }

    func makeProfileScreen(
        mode: ProfileScreen.Mode,
        startSignInFlow: @escaping (Bool) -> Void,
        bottomContentPadding: CGFloat
    ) -> some View {
        ProfileScreen(
            mode: mode,
            startSignInFlow: startSignInFlow,
            bottomContentPadding: bottomContentPadding
        )
    }

    func makeAviScreen(
        currentStation: Station?,
        focusedStation: Station?,
        isFocusedStationActive: Bool,
        currentTrackTitle: String?,
        currentTrackArtist: String?,
        currentTrackArtworkURL: URL?,
        isPlaying: Bool,
        isLoading: Bool,
        activeSleepTimerMinutes: Int?,
        activeSleepTimerRemainingMinutes: Int?,
        canCyclePlaybackQueue: Bool,
        playbackQueueSource: AudioPlayerService.PlaybackQueue.Source,
        playbackQueueStations: [Station],
        stations: [Station],
        recentStations: [Station],
        favoriteStations: [Station],
        discoveries: [DiscoveredTrack],
        focusedMusicDetail: SelectedMusicAviDetail?,
        isNowPlayingFullPlayer: Bool,
        focusedStationDetailSection: StationDetailSection,
        isActionPanelOpen: Binding<Bool>,
        stationFeedback: [String: TuneAVStationFeedback],
        feedContext: HomeFeedContext,
        preferredTag: String,
        preferredCountryCode: String,
        bottomContentPadding: CGFloat,
        openSearch: @escaping () -> Void,
        openLibrary: @escaping () -> Void,
        openPlayer: @escaping () -> Void,
        stopPlayback: @escaping () -> Void,
        setSleepTimer: @escaping (Int?) -> Void,
        playPrevious: @escaping () -> Void,
        playNext: @escaping () -> Void,
        playStation: @escaping (Station, [Station]) -> Void,
        playStationFromQueue: @escaping (Station, AudioPlayerService.PlaybackQueue.Source, [Station]) -> Void,
        toggleFavorite: @escaping (Station) -> Void,
        setStationFeedback: @escaping (Station, TuneAVStationFeedback?) -> Void,
        showStationDetails: @escaping (Station, [Station]) -> Void,
        openDiscoveryInfo: @escaping (DiscoveredTrack) -> Void,
        openDiscoveryStation: @escaping (DiscoveredTrack) -> Void,
        openAccount: @escaping () -> Void,
        startSignIn: @escaping () -> Void,
        openProPaywall: @escaping () -> Void,
        closeFocusedDetail: @escaping () -> Void
    ) -> some View {
        AviScreen(
            currentStation: currentStation,
            focusedStation: focusedStation,
            isFocusedStationActive: isFocusedStationActive,
            currentTrackTitle: currentTrackTitle,
            currentTrackArtist: currentTrackArtist,
            currentTrackArtworkURL: currentTrackArtworkURL,
            isPlaying: isPlaying,
            isLoading: isLoading,
            activeSleepTimerMinutes: activeSleepTimerMinutes,
            activeSleepTimerRemainingMinutes: activeSleepTimerRemainingMinutes,
            canCyclePlaybackQueue: canCyclePlaybackQueue,
            playbackQueueSource: playbackQueueSource,
            playbackQueueStations: playbackQueueStations,
            stations: stations,
            recentStations: recentStations,
            favoriteStations: favoriteStations,
            discoveries: discoveries,
            focusedMusicDetail: focusedMusicDetail,
            isNowPlayingFullPlayer: isNowPlayingFullPlayer,
            focusedStationDetailSection: focusedStationDetailSection,
            isActionPanelOpen: isActionPanelOpen,
            stationFeedback: stationFeedback,
            feedContext: feedContext,
            preferredTag: preferredTag,
            preferredCountryCode: preferredCountryCode,
            bottomContentPadding: bottomContentPadding,
            openSearch: openSearch,
            openLibrary: openLibrary,
            openPlayer: openPlayer,
            stopPlayback: stopPlayback,
            setSleepTimer: setSleepTimer,
            playPrevious: playPrevious,
            playNext: playNext,
            playStation: playStation,
            playStationFromQueue: playStationFromQueue,
            toggleFavorite: toggleFavorite,
            setStationFeedback: setStationFeedback,
            showStationDetails: showStationDetails,
            openDiscoveryInfo: openDiscoveryInfo,
            openDiscoveryStation: openDiscoveryStation,
            openAccount: openAccount,
            startSignIn: startSignIn,
            openProPaywall: openProPaywall,
            closeFocusedDetail: closeFocusedDetail
        )
    }
}
