import AVAppShellFoundation
import SwiftUI

typealias TuneLayoutClass = AVAppShellLayoutClass
typealias TuneLayoutContext = AVAppShellLayoutContext
typealias TuneAdaptiveLayoutReader = AVAppShellAdaptiveLayoutReader
