#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_path="$repo_root/apps/ios/Config/Local.xcconfig"
source_label="CI"

usage() {
  cat <<'USAGE'
Usage:
  scripts/generate-ios-ci-release-xcconfig.sh [--source <label>]

Generates the ignored iOS production Local.xcconfig from CI environment
variables. The script validates required secret shape without printing values.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --source)
      source_label="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

required_vars=(
  ACCOUNTAV_API_BASE_URL
  ACCOUNTAV_MANAGEMENT_URL
  ACCOUNTAV_PUBLISHABLE_KEY
  TUNEAV_CONVEX_URL
  TUNEAV_REVENUECAT_PUBLIC_API_KEY
  TUNEAV_REVENUECAT_OFFERING_ID
  TUNEAV_REVENUECAT_MONTHLY_PACKAGE_ID
)

missing=0
for name in "${required_vars[@]}"; do
  if [ -z "${!name:-}" ]; then
    echo "FAIL missing $name." >&2
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  exit 1
fi

case "$ACCOUNTAV_API_BASE_URL" in
  https://*) ;;
  *) echo "FAIL ACCOUNTAV_API_BASE_URL must use HTTPS." >&2; exit 1 ;;
esac
case "$ACCOUNTAV_MANAGEMENT_URL" in
  https://*) ;;
  *) echo "FAIL ACCOUNTAV_MANAGEMENT_URL must use HTTPS." >&2; exit 1 ;;
esac
case "$TUNEAV_CONVEX_URL" in
  https://*.convex.cloud) ;;
  *) echo "FAIL TUNEAV_CONVEX_URL must be a Convex cloud URL." >&2; exit 1 ;;
esac
case "$ACCOUNTAV_PUBLISHABLE_KEY" in
  pk_live_*) ;;
  *) echo "FAIL ACCOUNTAV_PUBLISHABLE_KEY must start with pk_live_." >&2; exit 1 ;;
esac
case "$TUNEAV_REVENUECAT_PUBLIC_API_KEY" in
  appl_*) ;;
  *) echo "FAIL TUNEAV_REVENUECAT_PUBLIC_API_KEY must start with appl_." >&2; exit 1 ;;
esac
case "$TUNEAV_REVENUECAT_PUBLIC_API_KEY" in
  sk_*) echo "FAIL TUNEAV_REVENUECAT_PUBLIC_API_KEY must not be a RevenueCat secret key." >&2; exit 1 ;;
esac

escape_xcconfig_url() {
  printf '%s' "$1" | sed 's#/#$(XCCONFIG_SLASH)#g'
}

tuneav_revenuecat_offering_id="$TUNEAV_REVENUECAT_OFFERING_ID"
tuneav_revenuecat_monthly_package_id="$TUNEAV_REVENUECAT_MONTHLY_PACKAGE_ID"
tuneav_premium_product_ids="${TUNEAV_PREMIUM_PRODUCT_IDS:-tuneav_pro_monthly}"
support_email_to="${SUPPORT_EMAIL_TO:-support@avalsys.com}"
supportav_base_url="${SUPPORTAV_BASE_URL:-https://support-av.avalsys.com}"

umask 077
mkdir -p "$(dirname "$output_path")"
cat > "$output_path" <<EOF
// GENERATED by $source_label
// Do not commit this file.
XCCONFIG_SLASH = /
TUNEAV_CONFIG_ENVIRONMENT = prod
TUNEAV_BUNDLE_IDENTIFIER = com.avalsys.tuneav
AVALSYS_APPLE_DEVELOPMENT_TEAM = \$(inherited)
ACCOUNTAV_PUBLISHABLE_KEY = $ACCOUNTAV_PUBLISHABLE_KEY
TUNEAV_PREMIUM_PRODUCT_IDS = $tuneav_premium_product_ids
SUPPORT_EMAIL_TO = $support_email_to
SUPPORTAV_BASE_URL = $(escape_xcconfig_url "$supportav_base_url")
ACCOUNTAV_API_BASE_URL = $(escape_xcconfig_url "$ACCOUNTAV_API_BASE_URL")
TUNEAV_CONVEX_URL = $(escape_xcconfig_url "$TUNEAV_CONVEX_URL")
TUNEAV_ENABLE_LISTENING_ANALYTICS_UPLOADS = 1
ACCOUNTAV_MANAGEMENT_URL = $(escape_xcconfig_url "$ACCOUNTAV_MANAGEMENT_URL")
TUNEAV_DELETE_ACCOUNT_URL = https:\$(XCCONFIG_SLASH)\$(XCCONFIG_SLASH)tune-av.avalsys.com\$(XCCONFIG_SLASH)delete-account
TUNEAV_TERMS_URL = https:\$(XCCONFIG_SLASH)\$(XCCONFIG_SLASH)tune-av.avalsys.com\$(XCCONFIG_SLASH)terms
TUNEAV_PRIVACY_URL = https:\$(XCCONFIG_SLASH)\$(XCCONFIG_SLASH)tune-av.avalsys.com\$(XCCONFIG_SLASH)privacy
TUNEAV_OPEN_SOURCE_URL = https:\$(XCCONFIG_SLASH)\$(XCCONFIG_SLASH)github.com\$(XCCONFIG_SLASH)miguelavalos\$(XCCONFIG_SLASH)tune-av
TUNEAV_REVENUECAT_PUBLIC_API_KEY = $TUNEAV_REVENUECAT_PUBLIC_API_KEY
TUNEAV_REVENUECAT_OFFERING_ID = $tuneav_revenuecat_offering_id
TUNEAV_REVENUECAT_MONTHLY_PACKAGE_ID = $tuneav_revenuecat_monthly_package_id
TUNEAV_IOS_SENTRY_DSN = ${TUNEAV_IOS_SENTRY_DSN:-}
EOF

chmod 600 "$output_path"
echo "Generated apps/ios/Config/Local.xcconfig for production release checks."
